name: Run Tests
on: push

jobs:
  pytest:
    name: pytest
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Install
      uses: abatilo/actions-poetry@v1.8.0
      with:
        python_version: 3.7
        poetry_version: 1.0
        args: install
    - name: Run pytest
      uses: abatilo/actions-poetry@v1.8.0
      with:
        python_version: 3.7
        poetry_version: 1.0
        working_directory: ./tests
        args: run python -m pytest --cov=src --cov-branch